image: gcr.io/kaniko-project/executor:debug

build-perfsonar:
  stage: build
  variables:
    PROJECT_CONTEXT: "perfsonar"
  script:
    - echo "=== $CI_COMMIT_BRANCH $CI_COMMIT_TAG $CI_COMMIT_SHA $CI_REGISTRY_IMAGE/$PROJECT_CONTEXT:latest $(hostname) $(date)"
    - echo "{\"auths\":{\"$CI_REGISTRY\":{\"username\":\"$CI_REGISTRY_USER\",\"password\":\"$CI_REGISTRY_PASSWORD\"}}}" > /kaniko/.docker/config.json
    - mv /var/run /run && ln -sf -v ../run /var/run # fix to match Kaniko image
    - /kaniko/executor --cache=true --context git://github.com/perfsonar/perfsonar-testpoint-docker#refs/heads/5.0.0 --destination $CI_REGISTRY_IMAGE/$PROJECT_CONTEXT:${CI_COMMIT_SHA:0:8} --destination $CI_REGISTRY_IMAGE/$PROJECT_CONTEXT:latest
