apiVersion: v1
kind: Pod
metadata:
  name: home
  labels:
    home: home-pod
spec:
  containers:
  - name: home
    image: debian:11
    resources:
      requests:
        memory: 1Gi
        cpu: 1
      limits:
        memory: 1Gi
        cpu: 1
    volumeMounts:
      - mountPath: /home
        name: home
    command: [ tail ]
    args: [ -F, /var/log/container.log  ]
  volumes:
    - name: home
      persistentVolumeClaim:
        claimName: home-data
