apiVersion: v1
kind: Pod
metadata:
  name: home
  labels:
    home: home-pod
spec:
  containers:
  - name: home
    image: debian:10
    resources:
      limits:
        memory: 384Mi
        cpu: 250m
      requests:
        cpu: 200m
        memory: 256Mi
    volumeMounts:
      - mountPath: /home
        name: home
    command: [ sleep ]
    args: [ 2h ]
  volumes:
    - name: home
      persistentVolumeClaim:
        claimName: home-data
