apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: home-data
  labels:
    app: home-data
spec:
  storageClassName: rook-ceph-block
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
---
apiVersion: v1
kind: Pod
metadata:
  name: home
  labels:
    app: home-pod
spec:
  containers:
  - name: home
    image: gitlab-registry.nrp-nautilus.io/$USER/$PROJECT/home:latest
    resources:
      requests:
        memory: 4Gi  # 256Mi
        cpu: 2000m   # 200m
        ephemeral-storage: 5Gi
      limits:
        memory: 4Gi # 384Mi
        cpu: 2000m  # 250m
        ephemeral-storage: 5Gi
    volumeMounts:
      - name: home
        mountPath: /home
      - name: scratch
        mountPath: /scratch
    command: [ tail ]
    args: [ -F, /var/log/container.log  ]
  volumes:
    - name: home
      persistentVolumeClaim:
        claimName: home-data
    - name: scratch
      emptyDir: {}
  imagePullSecrets:
    - name: home-deploy-token
