apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: home-data
  labels:
    home: home-data
spec:
  storageClassName: rook-ceph-block
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
---
apiVersion: v1
kind: Pod
metadata:
  name: home
  labels:
    home: home-pod
spec:
  containers:
  - name: home
    image: gitlab-registry.nautilus.optiputer.net/$USER/$PROJECT/home:latest
    resources:
      limits:
        memory: 384Mi
        cpu: 250m
        ephemeral-storage: 5Gi
      requests:
        memory: 256Mi
        cpu: 200m
        ephemeral-storage: 5Gi
    volumeMounts:
      - name: home
        mountPath: /home
      - name: scratch
        mountPath: /scratch
    command: [ sleep ]
    args: [ 2h ]
  volumes:
    - name: home
      persistentVolumeClaim:
        claimName: home-data
    - name: scratch
      emptyDir: {}
  imagePullSecrets:
    - name: home-deploy-token
