apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: home-data
  labels:
    home: home-data
spec:
  storageClassName: rook-ceph-block
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
